/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class adf_AdfLibrary */

#ifndef _Included_adf_AdfLibrary
#define _Included_adf_AdfLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     adf_AdfLibrary
 * Method:    adfSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_adf_AdfLibrary_adfSize
  (JNIEnv *, jobject);

/*
 * Class:     adf_AdfLibrary
 * Method:    marshal
 * Signature: (Ladf/Adf;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_adf_AdfLibrary_marshal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     adf_AdfLibrary
 * Method:    unmarshal
 * Signature: ([B)Ladf/Adf;
 */
JNIEXPORT jobject JNICALL Java_adf_AdfLibrary_unmarshal
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
