name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare environment for C compiling
      run: sudo apt-get install build-essential 
    - name: generate sample
      run: make init
    - name: make library and execute tests
      run: make
    - name: install
      run: sudo make install
    - name: make example
      run: (cd example && make example)
